<?xml version="1.0" encoding="utf-8"?><Database Name="QLNhaTro" Class="dbNhaTroDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CASMAP;Initial Catalog=QLNhaTro;User ID=sa" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="QLNhaTroConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_KH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Phong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GiaPhong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SkDien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienDien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SkNuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienNuoc" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TienDV" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="ID_KH" OtherKey="ID" Type="KhachHang" IsForeignKey="true" />
      <Association Name="Phong_HoaDon" Member="Phong" ThisKey="ID_Phong" OtherKey="ID" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TraPhong" Member="TraPhongs">
    <Type Name="TraPhong">
      <Column Name="ID_Thue" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_KH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Phong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayThue" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ThuePhong_TraPhong" Member="ThuePhong" ThisKey="ID_Thue,ID_KH" OtherKey="ID,ID_KH" Type="ThuePhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="ID" OtherKey="ID_KH" Type="HoaDon" />
      <Association Name="KhachHang_ThuePhong" Member="ThuePhongs" ThisKey="ID" OtherKey="ID_KH" Type="ThuePhong" />
      <Association Name="Phong_KhachHang" Member="Phong" ThisKey="MaPhong" OtherKey="ID" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phi" Member="Phis">
    <Type Name="Phi">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhi" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuePhong" Member="ThuePhongs">
    <Type Name="ThuePhong">
      <Column Name="ID" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_KH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Phong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayThue" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TienCoc" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="ThuePhong_TraPhong" Member="TraPhong" ThisKey="ID,ID_KH" OtherKey="ID_Thue,ID_KH" Type="TraPhong" Cardinality="One" />
      <Association Name="KhachHang_ThuePhong" Member="KhachHang" ThisKey="ID_KH" OtherKey="ID" Type="KhachHang" IsForeignKey="true" />
      <Association Name="Phong_ThuePhong" Member="Phong" ThisKey="ID_Phong" OtherKey="ID" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="ID" OtherKey="IDLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDLoaiPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiToiDa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Phong_HoaDon" Member="HoaDons" ThisKey="ID" OtherKey="ID_Phong" Type="HoaDon" />
      <Association Name="Phong_KhachHang" Member="KhachHangs" ThisKey="ID" OtherKey="MaPhong" Type="KhachHang" />
      <Association Name="Phong_ThuePhong" Member="ThuePhongs" ThisKey="ID" OtherKey="ID_Phong" Type="ThuePhong" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="IDLoaiPhong" OtherKey="ID" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThamSo" Member="ThamSos">
    <Type Name="ThamSo">
      <Column Name="ID" Type="System.String" DbType="NVarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ThemPhi" Method="ThemPhi">
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="GiaTien" Parameter="giaTien" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XemCacLoaiPhi" Method="XemCacLoaiPhi">
    <ElementType Name="XemCacLoaiPhiResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhi" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XoaPhi" Method="XoaPhi">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaPhi" Method="SuaPhi">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="GiaTien" Parameter="giaTien" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemLP" Method="ThemLP">
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Gia" Parameter="gia" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaLP" Method="SuaLP">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Gia" Parameter="gia" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaLP" Method="XoaLP">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LayDSLoaiPhong" Method="LayDSLoaiPhong">
    <ElementType Name="LayDSLoaiPhongResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenLP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThemPhong" Method="ThemPhong">
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Loai" Parameter="loai" Type="System.Int32" DbType="Int" />
    <Parameter Name="ToiDa" Parameter="toiDa" Type="System.Int32" DbType="Int" />
    <Parameter Name="HienTai" Parameter="hienTai" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaPhong" Method="SuaPhong">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Loai" Parameter="loai" Type="System.Int32" DbType="Int" />
    <Parameter Name="ToiDa" Parameter="toiDa" Type="System.Int32" DbType="Int" />
    <Parameter Name="HienTai" Parameter="hienTai" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XemDSPhong" Method="XemDSPhong">
    <ElementType Name="XemDSPhongResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenLP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiToiDa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.XoaPhong" Method="XoaPhong">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LayPhongTrongTheoLoai" Method="LayPhongTrongTheoLoai">
    <Parameter Name="idLoai" Type="System.Int32" DbType="Int" />
    <ElementType Name="LayPhongTrongTheoLoaiResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDLoaiPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiToiDa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.KTPhongTonTai" Method="KTPhongTonTai">
    <Parameter Name="idPhong" Type="System.Int32" DbType="Int" />
    <Parameter Name="kq" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaSoNguoiHienTai" Method="SuaSoNguoiHienTai">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="HienTai" Parameter="hienTai" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LaySoNguoiHTVaTD" Method="LaySoNguoiHTVaTD">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ToiDa" Parameter="toiDa" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="HienTai" Parameter="hienTai" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KTIdKhachHangToiTai" Method="KTIdKhachHangToiTai">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="kq" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaKH" Method="SuaKH">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Sdt" Parameter="sdt" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="QueQuan" Parameter="queQuan" Type="System.String" DbType="NVarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LayMa" Method="LayMa">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="giaTri" Type="System.String" DbType="NVarChar(8)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KTLoaiTonTai" Method="KTLoaiTonTai">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="kq" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LayPhongTheoTen" Method="LayPhongTheoTen">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="LayPhongTheoTenResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDLoaiPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiToiDa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.KTKHCoTraPhong" Method="KTKHCoTraPhong">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="kq" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CapNhatMaPhongKH" Method="CapNhatMaPhongKH">
    <Parameter Name="idKH" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="maPhong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemThuePhong" Method="ThemThuePhong">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="idKH" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="idPhong" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngayThue" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="tienCoc" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemKH" Method="ThemKH">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Sdt" Parameter="sdt" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="QueQuan" Parameter="queQuan" Type="System.String" DbType="NVarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CapNhatThamSo" Method="CapNhatThamSo">
    <Parameter Name="id" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="giaTri" Type="System.String" DbType="NVarChar(8)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LayDSPhongChuaLapHoaDon" Method="LayDSPhongChuaLapHoaDon">
    <Parameter Name="nam" Type="System.String" DbType="NVarChar(4)" />
    <Parameter Name="thang" Type="System.String" DbType="NVarChar(2)" />
    <ElementType Name="LayDSPhongChuaLapHoaDonResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDLoaiPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiToiDa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNguoiHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThemHoaDon" Method="ThemHoaDon">
    <Parameter Name="ID_KH" Parameter="iD_KH" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ID_Phong" Parameter="iD_Phong" Type="System.Int32" DbType="Int" />
    <Parameter Name="NgayLap" Parameter="ngayLap" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="GiaPhong" Parameter="giaPhong" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SkDien" Parameter="skDien" Type="System.Int32" DbType="Int" />
    <Parameter Name="TienDien" Parameter="tienDien" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SkNuoc" Parameter="skNuoc" Type="System.Int32" DbType="Int" />
    <Parameter Name="TienNuoc" Parameter="tienNuoc" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="TienDV" Parameter="tienDV" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="TongTien" Parameter="tongTien" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.fChuyenCoDauThanhKhongDau" Method="fChuyenCoDauThanhKhongDau" IsComposable="true">
    <Parameter Name="inputVar" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.TimKhachThue" Method="TimKhachThue">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="TimKhachThueResult">
      <Column Name="ID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThemTraPhong" Method="ThemTraPhong">
    <Parameter Name="idThue" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="idKH" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="idPhong" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngayThue" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ngayTra" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CapNhatMaPhongNUll" Method="CapNhatMaPhongNUll">
    <Parameter Name="idKH" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
</Database>